//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18408
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reporting.RdlDesign {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
	internal sealed partial class Toolbars : global::System.Configuration.ApplicationSettingsBase
{
private static Toolbars defaultInstance = ((Toolbars)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Toolbars())));
public static Toolbars Default
{
get { return defaultInstance; }
}
[global::System.Configuration.UserScopedSettingAttribute()]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
public global::System.Drawing.Point FontPos
{
get { return ((global::System.Drawing.Point)(this["FontPos"])); }
set { this["FontPos"] = value; }
}
[global::System.Configuration.UserScopedSettingAttribute()]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
public global::System.Drawing.Point FormPos
{
get { return ((global::System.Drawing.Point)(this["FormPos"])); }
set { this["FormPos"] = value; }
}
[global::System.Configuration.UserScopedSettingAttribute()]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Configuration.DefaultSettingValueAttribute("714, 457")]
public global::System.Drawing.Size FormSize
{
get { return ((global::System.Drawing.Size)(this["FormSize"])); }
set { this["FormSize"] = value; }
}
[global::System.Configuration.UserScopedSettingAttribute()]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Configuration.DefaultSettingValueAttribute("Normal")]
public global::System.Windows.Forms.FormWindowState FormState
{
get { return ((global::System.Windows.Forms.FormWindowState)(this["FormState"])); }
set { this["FormState"] = value; }
}
[global::System.Configuration.UserScopedSettingAttribute()]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
public global::System.Drawing.Point InsertPos
{
get { return ((global::System.Drawing.Point)(this["InsertPos"])); }
set { this["InsertPos"] = value; }
}
[global::System.Configuration.UserScopedSettingAttribute()]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Configuration.DefaultSettingValueAttribute("True")]
public bool ShowFont
{
get { return ((bool)(this["ShowFont"])); }
set { this["ShowFont"] = value; }
}
[global::System.Configuration.UserScopedSettingAttribute()]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Configuration.DefaultSettingValueAttribute("True")]
public bool ShowInsert
{
get { return ((bool)(this["ShowInsert"]));}
set { this["ShowInsert"] = value; }
}
[global::System.Configuration.UserScopedSettingAttribute()]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Configuration.DefaultSettingValueAttribute("True")]
public bool ShowStandard
{
get { return ((bool)(this["ShowStandard"])); }
set { this["ShowStandard"] = value; }
}
[global::System.Configuration.UserScopedSettingAttribute()]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Configuration.DefaultSettingValueAttribute("True")]
public bool ShowZoom
{
get { return ((bool)(this["ShowZoom"])); }
set { this["ShowZoom"] = value; }
}
[global::System.Configuration.UserScopedSettingAttribute()]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
public global::System.Drawing.Point StandardPos
{
get { return ((global::System.Drawing.Point)(this["StandardPos"])); }
set { this["StandardPos"] = value; }
}
[global::System.Configuration.UserScopedSettingAttribute()]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
public global::System.Drawing.Point ZoomPos
{
get { return ((global::System.Drawing.Point)(this["ZoomPos"])); }
set { this["ZoomPos"] = value; }
}
}
} 